-- MySQL 8.0.16+ (verified on MySQL 8.0.46).
-- setup.py safely substitutes this database identifier from DB_NAME in .env.
CREATE DATABASE IF NOT EXISTS `VehicleSalesDB` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `VehicleSalesDB`;

CREATE TABLE IF NOT EXISTS roles (
 role_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 role_name VARCHAR(80) NOT NULL UNIQUE,
 description VARCHAR(250) NOT NULL DEFAULT '',
 is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS permissions (
 permission_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 permission_name VARCHAR(100) NOT NULL UNIQUE,
 module VARCHAR(50) NOT NULL,
 action VARCHAR(50) NOT NULL,
 description VARCHAR(250) NOT NULL DEFAULT '',
 is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS role_permissions (
 role_id INT UNSIGNED NOT NULL,
 permission_id INT UNSIGNED NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (role_id, permission_id),
 FOREIGN KEY (role_id) REFERENCES roles(role_id),
 FOREIGN KEY (permission_id) REFERENCES permissions(permission_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS users (
 user_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(80) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 full_name VARCHAR(250) NOT NULL,
 email VARCHAR(250) NULL UNIQUE,
 is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_roles (
 user_id INT UNSIGNED NOT NULL,
 role_id INT UNSIGNED NOT NULL,
 assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (user_id, role_id),
 FOREIGN KEY (user_id) REFERENCES users(user_id),
 FOREIGN KEY (role_id) REFERENCES roles(role_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS customers (
 customer_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 customer_code VARCHAR(80) NOT NULL UNIQUE,
 full_name VARCHAR(250) NOT NULL,
 phone VARCHAR(80) NOT NULL,
 email VARCHAR(250) NOT NULL,
 address VARCHAR(250) NOT NULL DEFAULT '',
 is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS vehicles (
 vehicle_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 vehicle_code VARCHAR(80) NOT NULL UNIQUE,
 vin VARCHAR(17) NULL UNIQUE,
 plate_number VARCHAR(80) NULL UNIQUE,
 brand VARCHAR(100) NOT NULL,
 model VARCHAR(150) NOT NULL,
 vehicle_year SMALLINT UNSIGNED NOT NULL,
 color VARCHAR(100) NOT NULL,
 purchase_price DECIMAL(14,2) NOT NULL,
 selling_price DECIMAL(14,2) NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
 image_path VARCHAR(250) NOT NULL DEFAULT 'sedan.svg',
 mileage INT UNSIGNED NOT NULL DEFAULT 0,
 fuel VARCHAR(80) NOT NULL DEFAULT 'Not specified',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT vehicle_prices CHECK (purchase_price >= 0 AND selling_price >= 0),
 CONSTRAINT vehicle_status CHECK (status IN ('AVAILABLE','RESERVED','SOLD','INACTIVE')),
 CONSTRAINT vehicle_vin CHECK (vin IS NULL OR CHAR_LENGTH(vin) = 17),
 INDEX vehicle_filters (status, brand, vehicle_year)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS stock_movements (
 movement_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 vehicle_id INT UNSIGNED NOT NULL,
 user_id INT UNSIGNED NOT NULL,
 movement_type VARCHAR(20) NOT NULL,
 movement_date DATE NOT NULL,
 reason VARCHAR(250) NOT NULL,
 quantity SMALLINT NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id),
 FOREIGN KEY (user_id) REFERENCES users(user_id),
 CONSTRAINT movement_delta CHECK ((movement_type='STOCK_IN' AND quantity=1) OR (movement_type='STOCK_OUT' AND quantity=-1) OR (movement_type='ADJUSTMENT' AND quantity=0)),
 INDEX movement_dates (movement_date, movement_type)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS sales (
 sale_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 sale_code VARCHAR(80) NOT NULL UNIQUE,
 user_id INT UNSIGNED NOT NULL,
 customer_id INT UNSIGNED NOT NULL,
 vehicle_id INT UNSIGNED NOT NULL UNIQUE,
 sale_date DATE NOT NULL,
 sale_price DECIMAL(14,2) NOT NULL,
 discount_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
 total_amount DECIMAL(14,2) NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(user_id),
 FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
 FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id),
 CONSTRAINT sale_amounts CHECK (sale_price >= 0 AND discount_amount >= 0 AND discount_amount <= sale_price AND total_amount = sale_price-discount_amount),
 CONSTRAINT sale_status CHECK (status IN ('PENDING','COMPLETED','CANCELLED')),
 INDEX sales_dates (status, sale_date)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS invoices (
 invoice_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 invoice_number VARCHAR(80) NOT NULL UNIQUE,
 sale_id INT UNSIGNED NOT NULL UNIQUE,
 issue_date DATE NOT NULL,
 total_amount DECIMAL(14,2) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (sale_id) REFERENCES sales(sale_id),
 CONSTRAINT invoice_amount CHECK (total_amount >= 0),
 INDEX invoice_dates (issue_date)
) ENGINE=InnoDB;
